"""empty message

Revision ID: 054f3ea4a484
Revises: f852ed118f43
Create Date: 2022-08-06 17:26:16.200226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054f3ea4a484'
down_revision = 'f852ed118f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'photo')
    # ### end Alembic commands ###
