"""empty message

Revision ID: 67da8fbf47f9
Revises: 6181a8b6cba4
Create Date: 2022-08-05 13:25:42.565492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67da8fbf47f9'
down_revision = '6181a8b6cba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pokemon_user_id_fkey', 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'user_id')
    op.drop_constraint('user_pokemon_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pokemon', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_pokemon_fkey', 'user', 'pokemon', ['pokemon'], ['id'])
    op.add_column('pokemon', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pokemon_user_id_fkey', 'pokemon', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
